repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=5120]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  -   repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
      - id: darglint
        exclude: ^tests/.*$
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: ^tests/.*$
        additional_dependencies: ["toml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
  # - repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.3.1
  #   hooks:
  #     - id: nbqa-isort
  #       additional_dependencies: [isort==5.10.1]
  #     - id: nbqa-pyupgrade
  #       additional_dependencies: [pyupgrade==v2.32.0]
  #     - id: nbqa-black
  #       additional_dependencies: [black==22.3.0]
  #     - id: nbqa-flake8
  #       args: ["--extend-ignore=E402"]
  #       additional_dependencies: [flake8==3.9.2]
  #     - id: nbqa-mypy
  #       additional_dependencies: ["mypy==v0.942"]

