d_update_clip: .inf
dtype: torch.float32
eta: 0.01
in_c: 1
input_pad:
- 0
- 4
- 4
input_unit_var: true
input_zero_mean: true
kernel_odd: true
kh: 9
kt: 7
kw: 9
lambda_: 2
lat_conn_pad:
- 6
- 8
- 8
lca_iters: 1000
lca_tol: null
lca_warmup: 200
metric_fpath: linked_testing/metrics.xz
n_cells: 100
n_neurons: 140
no_time_pad: true
nonneg: true
pad: same
recon_output_pad:
- 0
- 1
- 1
req_grad: false
result_dir: linked_testing
return_all: false
stride_h: 2
stride_t: 1
stride_w: 2
tau: 1000
tau_decay_factor: 0.0
trace_inhib_pad: 0
trace_input_pad: 0
trace_kt: 7
trace_recon_pad: 0
trace_unit_var: false
trace_zero_mean: false
track_metrics: false
transfer_func: soft_threshold
